import swaggerAutogen from 'swagger-autogen';
import {envConfig} from "./src/config/env.config.js";

const doc = {
    info: {
        version: "1.0.0",
        title: envConfig.server.appName,
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: envConfig.server.host,
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
}

const outputFile = './api-swagger.json'
const routes = ['./src/routes/index.js']

// swaggerAutogen(outputFile, routes, doc) //swagger 2.0 specs  old

swaggerAutogen({openapi: '3.0.0'})(outputFile, routes, doc); //open api 3 new

//Gen at startup
// swaggerAutogen()(outputFile, routes, doc).then(async () => {
//     await import('./src/index.ts'); // Your project's root file
// });