import {envConfig} from "./config/env.config.js";
import 'dotenv/config';
import routes from "./routes/index.js";
import {initDatabase} from "./db/dbSetup.js";
import {standardLimiter} from "./middleware/rate-limit.js";
import {requestLogger} from "./middleware/request-logger.js";
import {errorHandler, notFoundHandler} from "./utils/error-handler.js";
import {logger} from "./utils/logger.js";
import {toNodeHandler} from "better-auth/node";
import cors from "cors";
import corsOptions from "./config/cors.config.js";
import express from "express";
import swaggerUi from 'swagger-ui-express';
import helmet from "helmet";
import {auth} from "./utils/auth.js";
import {readFileSync} from 'node:fs';



// checkEnv(env);

let swaggerApiDocument, swaggerAuthApiDocument
const authHandler = toNodeHandler(auth);


/*
   INITIALIZE EXPRESS APPLICATION 🏁
*/
export const app = express();

/*
   APPLICATION MIDDLEWARE AND CUSTOMIZATIONS 🪛
*/
app.disable("x-powered-by"); // Disable X-Powered-By header in responses
// app.use(cors(corsOptions)); // Enable Cross Origin Resource Sharing
// app.options("/{*any}", cors(corsOptions))
// Trust proxy for accurate IP addresses
app.set('trust proxy', 1);
//Logging
// app.use(requestLogger);
// Apply rate limiting to all requests
app.use(standardLimiter);

// BetterAuth handler with additional debugging
app.all('/api/auth/*splat', (req, res) => {
    logger.info(`🔐 BetterAuth handling: ${req.method} ${req.url}`);
    logger.info('🔐 Request body:', req.body);

    authHandler(req, res).catch(err => {
        console.error('BetterAuth handler error:', err);
        res.status(500).json({error: 'Internal auth error'});
    });
});

// Register better-auth route BEFORE body parsers and helmet
// Mount express json middleware after Better Auth handler
// or only apply it to routes that don't interact with Better Auth
app.use(express.json());
app.use(helmet());
app.use(express.urlencoded({extended: true}));

/*
   APPLICATION ROUTES 🛣️
*/
app.use("/api", routes);

// Generate Swagger docs and ui
if (process.env.NODE_ENV === 'development') {
    //Api Docs - You must generate api-swagger.json file by running npm run swagger
    try {
        swaggerApiDocument = JSON.parse(readFileSync('./api-swagger.json', 'utf8'));
        if (swaggerApiDocument) {
            app.use('/api/api-docs', swaggerUi.serveFiles(swaggerApiDocument), swaggerUi.setup(swaggerApiDocument));
            logger.info('api-swagger.json loaded successfully!');
        }
    } catch (err) {
        logger.error(`Error reading JSON file: ${err}`);
    }

    //better-auth-api-docs better-auth-api-swagger.json file is automatically generated by better-auth plugin openapi
    try {
        swaggerAuthApiDocument = JSON.parse(readFileSync('./better-auth-api-swagger.json', 'utf8'));
        if (swaggerAuthApiDocument) {
            app.use('/api/auth-api-docs', swaggerUi.serveFiles(swaggerAuthApiDocument), swaggerUi.setup(swaggerAuthApiDocument));
            logger.info('better-auth-api-swagger.json loaded successfully!');
        }
    } catch (err) {
        logger.error(`Error reading JSON file: ${err}`);
    }

    //Test better-auth
    logger.info('🔧 Testing BetterAuth configuration...');
    try {
        await auth.api.getSession({
            headers: new Headers({
                'Content-Type': 'application/json',
            }),
        });
        logger.info('✅ BetterAuth configuration is valid');
    } catch (error) {
        console.error('❌ BetterAuth configuration error:', error);
    }
}


// 404 handler
app.use(notFoundHandler);

// Global error handler
app.use(errorHandler);

// Start the server
const startServer = async () => {
    try {
        // Initialize database connection
        await initDatabase();
        // Start listening for requests
        app.listen(envConfig.server.port, envConfig.server.host, () => {
            logger.info(`🚀 Server running on http://${envConfig.server.host}:${envConfig.server.port}`);
            logger.info(`📚 API Documentation: http://${envConfig.server.host}:${envConfig.server.port}/api/auth-api-docs`);
            logger.info(`🔐 Auth endpoints: http://${envConfig.server.host}:${envConfig.server.port}/api/api-docs`);
            logger.info(`🔧 Environment: ${envConfig.server.env}`);
        });
    } catch (error) {
        logger.error("Failed to start server:", error);
        process.exit(1);
    }
};

// Handle unhandled rejections
process.on("unhandledRejection", (reason, promise) => {
    logger.error("Unhandled Rejection at:", {promise, reason});
});

// Handle uncaught exceptions
process.on("uncaughtException", (error) => {
    logger.error("Uncaught Exception:", error);
    process.exit(1);
});

// Start the server
startServer();

export default app;
